name: mephoto
favicon: null
layout_spectrum: 0.2020989661104977
typography_spectrum: 0.017193845938891172
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.012023478280752897
  lightness: 0.4391671121120453
  saturation: 0.8326479003299028
  rhythmicContrast: 0.9824340883642435
purpose: []
